#!/bin/bash

echo  "======= Setup .my Institution Radius Server (IRS) configuration ======="
echo -n "1) Input your reaml (e.g. 'usm.my) : "
read VAR_REALM
echo -n "2) Input your secret key (e.g. 'y0uRs3cr3t') : "
read VAR_SECRET_KEY
echo -n "3) Input your Freeradius 3 installation directory (left blank) : "
read VAR_INSTALL_PATH
echo -n "4) Input your host certificate private key file (example: '/etc/letsencrypt/live/idp.usm.my/privkey.pem') : "
read PRIV_KEY_FILE
echo -n "5) Input your host certificate public key file (example: '/etc/letsencrypt/live/idp.usm.my/cert.pem') : "
read PUBLIC_KEY_FILE
echo -n "6) Input your host certificate ca key file (example: '/etc/letsencrypt/live/idp.usm.my/fullchain.pem') : "
read CA_KEY_FILE

echo -e "\nConfiguring eap modules script....\n"
#eap setup
awk -v -vPRIV_KEY_FILE=$PRIV_KEY_FILE -vPUBLIC_KEY_FILE=$PUBLIC_KEY_FILE -vCA_KEY_FILE=$CA_KEY_FILE '{gsub("PRIV_KEY_FILE", PRIV_KEY_FILE); gsub("PUBLIC_KEY_FILE", PUBLIC_KEY_FILE); gsub("CA_KEY_FILE", CA_KEY_FILE);print}' mods-available/eap.temp > mods-available/eap

#clients.conf setup
awk -vVAR_REALM=$VAR_REALM -vVAR_SECRET_KEY=$VAR_SECRET_KEY '{gsub("YOUR_REALM",VAR_REALM); gsub("EDUROAM_SECRET",VAR_SECRET_KEY); print}' clients.conf.temp > clients.conf

echo -e "\nConfiguring proxy.conf script....\n"
#proxy.conf setup
awk -vVAR_REALM=$VAR_REALM -vVAR_SECRET_KEY=$VAR_SECRET_KEY '{gsub("YOUR_REALM",VAR_REALM); gsub("EDUROAM_SECRET",VAR_SECRET_KEY); print}' proxy.conf.temp > proxy.conf

echo -e "\nConfiguring tunnel script....\n"
awk -vVAR_REALM=$VAR_REALM '{gsub("YOUR_REALM",VAR_REALM); print}' sites-available/eduroam.temp > sites-available/eduroam
cp -rf * $VAR_INSTALL_PATH/etc/raddb

echo -e "\nConfiguring fticks MY eduroam....\n"
#simbolic setup
cp f_ticks.temp $VAR_INSTALL_PATH/etc/raddb/mods-available/f_ticks
ln -s -f $VAR_INSTALL_PATH/etc/raddb/sites-available/eduroam $VAR_INSTALL_PATH/etc/raddb/sites-enabled/eduroam
ln -s -f $VAR_INSTALL_PATH/etc/raddb/mods-available/f_ticks $VAR_INSTALL_PATH/etc/raddb/mods-enabled/f_ticks

#install ca root certificate
cp ca-letsencrypt.pem $VAR_INSTALL_PATH/etc/raddb/certs/ca-letsencrypt.pem

echo -e "\ndone!!!"
